<a href="https://colab.research.google.com/github/mackeraldo/P-gina-de-erro/blob/main/Analise%20e%20Tratamento%20de%20dados%20de%20im%C3%B3veis%20do%20rio%20de%20janeiro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
dados = pd.read_csv('aluguel.csv', sep=";")

In [ ]:
dados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32960 entries, 0 to 32959
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Tipo        32960 non-null  object
 1   Bairro      32960 non-null  object
 2   Quartos     32960 non-null  int64
 3   Vagas       32960 non-null  int64
 4   Suites      32960 non-null  int64
 5   Area        32960 non-null  int64
 6   Valor       32943 non-null  float64
 7   Condominio  28867 non-null  float64
 8   IPTU        22723 non-null  float64
dtypes: float64(3), int64(4), object(2)
memory usage: 2.3+ MB

In [ ]:
tipo_de_dados  =pd.DataFrame(dados.dtypes,columns=['Tipo de dados']) #Criando um  dataframe somente com os tipos de dados

In [ ]:
tipo_de_dados

           Tipo de dados
Tipo              object
Bairro            object
Quartos            int64
Vagas              int64
Suites             int64
Area               int64
Valor            float64
Condominio       float64
IPTU             float64

In [ ]:
tipo_de_dados.columns.name = 'Variaveis' # Adicionando nome na coluna

In [ ]:
tipo_de_dados

Variaveis  Tipo de dados
Tipo              object
Bairro            object
Quartos            int64
Vagas              int64
Suites             int64
Area               int64
Valor            float64
Condominio       float64
IPTU             float64

In [ ]:
dados.shape #Mostra linhas e colunas

(32960, 9)

In [ ]:
print(f'A Base tem {dados.shape[0]} registros(Imóveis) e {dados.shape[1]} variáveis') # mistura texto e codigo

A Base tem 32960 registros(Imóveis) e 9 variáveis

In [ ]:
tipo_de_imoveis = dados['Tipo']

In [ ]:
type(tipo_de_imoveis)

pandas.core.series.Series

In [ ]:
tipo_de_imoveis

0                      Quitinete
1                           Casa
2        Conjunto Comercial/Sala
3                    Apartamento
4                    Apartamento
                  ...
32955                  Quitinete
32956                Apartamento
32957                Apartamento
32958                Apartamento
32959    Conjunto Comercial/Sala
Name: Tipo, Length: 32960, dtype: object

In [ ]:
tipo_de_imoveis.drop_duplicates(inplace = True) #Apaga os duplicados em series

In [ ]:
tipo_de_dados

Variaveis  Tipo de dados
Tipo              object
Bairro            object
Quartos            int64
Vagas              int64
Suites             int64
Area               int64
Valor            float64
Condominio       float64
IPTU             float64

In [ ]:
tipo_de_imoveis = pd.DataFrame(tipo_de_imoveis) #Criando dataFrame

In [ ]:
type(tipo_de_imoveis)

pandas.core.frame.DataFrame

In [ ]:
tipo_de_imoveis.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 22 entries, 0 to 23614
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Tipo    22 non-null     object
dtypes: object(1)
memory usage: 352.0+ bytes

In [ ]:
tipo_de_imoveis.index

Int64Index([    0,     1,     2,     3,     7,    16,    17,    29,    80,
               83,   117,   159,   207,   347,   589,  2157,  3354,  4379,
             4721,  6983,  9687, 23614],
           dtype='int64')

In [ ]:
tipo_de_imoveis.index = range(tipo_de_imoveis.shape[0])

In [ ]:
tipo_de_imoveis

                           Tipo
0                     Quitinete
1                          Casa
2       Conjunto Comercial/Sala
3                   Apartamento
4            Casa de Condomínio
5                Prédio Inteiro
6                          Flat
7                    Loja/Salão
8       Galpão/Depósito/Armazém
9                Casa Comercial
10                 Casa de Vila
11               Terreno Padrão
12                  Box/Garagem
13                         Loft
14  Loja Shopping/ Ct Comercial
15                      Chácara
16        Loteamento/Condomínio
17                        Sítio
18                Pousada/Chalé
19                       Studio
20                        Hotel
21                    Indústria

In [ ]:
tipo_de_imoveis.columns.name ='Id'

In [ ]:
tipo_de_imoveis

Id                         Tipo
0                     Quitinete
1                          Casa
2       Conjunto Comercial/Sala
3                   Apartamento
4            Casa de Condomínio
5                Prédio Inteiro
6                          Flat
7                    Loja/Salão
8       Galpão/Depósito/Armazém
9                Casa Comercial
10                 Casa de Vila
11               Terreno Padrão
12                  Box/Garagem
13                         Loft
14  Loja Shopping/ Ct Comercial
15                      Chácara
16        Loteamento/Condomínio
17                        Sítio
18                Pousada/Chalé
19                       Studio
20                        Hotel
21                    Indústria

Tratamento de Dados

In [ ]:
list(dados['Tipo'].drop_duplicates())

['Quitinete',
 'Casa',
 'Conjunto Comercial/Sala',
 'Apartamento',
 'Casa de Condomínio',
 'Prédio Inteiro',
 'Flat',
 'Loja/Salão',
 'Galpão/Depósito/Armazém',
 'Casa Comercial',
 'Casa de Vila',
 'Terreno Padrão',
 'Box/Garagem',
 'Loft',
 'Loja Shopping/ Ct Comercial',
 'Chácara',
 'Loteamento/Condomínio',
 'Sítio',
 'Pousada/Chalé',
 'Studio',
 'Hotel',
 'Indústria']

In [ ]:
residencial = ['Quitinete','Casa','Conjunto Comercial/Sala','Apartamento','Casa de Condomínio']

In [ ]:
residencial

['Quitinete',
 'Casa',
 'Conjunto Comercial/Sala',
 'Apartamento',
 'Casa de Condomínio']

In [ ]:
selecao = dados['Tipo'].isin(residencial)

In [ ]:
selecao

0        True
1        True
2        True
3        True
4        True
         ...
32955    True
32956    True
32957    True
32958    True
32959    True
Name: Tipo, Length: 32960, dtype: bool

In [ ]:
dados_residencial = dados[selecao]

In [ ]:
dados_residencial

,Tipo,Bairro,Quartos,Vagas,Suites,Area,Valor,Condominio,IPTU
0,Quitinete,Copacabana,1,0,0,40,1700.0,500.0,60.0
1,Casa,Jardim Botânico,2,0,1,100,7000.0,NaN,NaN
2,Conjunto Comercial/Sala,Barra da Tijuca,0,4,0,150,5200.0,4020.0,1111.0
3,Apartamento,Centro,1,0,0,15,800.0,390.0,20.0
4,Apartamento,Higienópolis,1,0,0,48,800.0,230.0,NaN
...,...,...,...,...,...,...,...,...,...
32955,Quitinete,Centro,0,0,0,27,800.0,350.0,25.0
32956,Apartamento,Jacarepaguá,3,1,2,78,1800.0,800.0,40.0
32957,Apartamento,São Francisco Xavier,2,1,0,48,1400.0,509.0,37.0
32958,Apartamento,Leblon,2,0,0,70,3000.0,760.0,NaN
32959,Conjunto Comercial/Sala,Centro,0,0,0,250,6500.0,4206.0,1109.0

In [ ]:
dados_residencial.index = range(dados_residencial.shape[0])

In [ ]:
dados_residencial

,Tipo,Bairro,Quartos,Vagas,Suites,Area,Valor,Condominio,IPTU
0,Quitinete,Copacabana,1,0,0,40,1700.0,500.0,60.0
1,Casa,Jardim Botânico,2,0,1,100,7000.0,NaN,NaN
2,Conjunto Comercial/Sala,Barra da Tijuca,0,4,0,150,5200.0,4020.0,1111.0
3,Apartamento,Centro,1,0,0,15,800.0,390.0,20.0
4,Apartamento,Higienópolis,1,0,0,48,800.0,230.0,NaN
...,...,...,...,...,...,...,...,...,...
29141,Quitinete,Centro,0,0,0,27,800.0,350.0,25.0
29142,Apartamento,Jacarepaguá,3,1,2,78,1800.0,800.0,40.0
29143,Apartamento,São Francisco Xavier,2,1,0,48,1400.0,509.0,37.0
29144,Apartamento,Leblon,2,0,0,70,3000.0,760.0,NaN
29145,Conjunto Comercial/Sala,Centro,0,0,0,250,6500.0,4206.0,1109.0

In [ ]:
# Número de imóvveis com tipo apartamento.

selacao = dados['Tipo'] == 'Apartamento'
n1 = dados[selecao].shape[0]

In [ ]:
n1

29146

In [ ]:
# imoveis classificados com tipo casa, casa de condominio e casa de vila.
selecao2 = (dados['Tipo'] == 'Casa') | (dados['Tipo'] == 'Casa de Condomínio') | (dados['Tipo'] == 'Casa de Vila')
n2 = dados[selecao2].shape[0]

In [ ]:
n2

2212

In [ ]:
# imoveis entre 60  e 100 m°
selecao3 =  (dados['Area'] >= 60) & (dados['Area'] <= 60)
n3 = dados[selecao3].shape[0]

In [ ]:
n3

922

In [ ]:
# imovveis com menos de 4 quartos e aluguel menos que 2 mil  reais
selecao4 = (dados['Quartos']<4) & (dados['Valor']<= 2000)
n4 = dados[selecao4].shape[0]

In [ ]:
n4

12758

In [ ]:
# Quais imoveis são estes ?
dados_residencial = dados[selecao4]
dados_residencial

,Tipo,Bairro,Quartos,Vagas,Suites,Area,Valor,Condominio,IPTU
0,Quitinete,Copacabana,1,0,0,40,1700.0,500.0,60.0
3,Apartamento,Centro,1,0,0,15,800.0,390.0,20.0
4,Apartamento,Higienópolis,1,0,0,48,800.0,230.0,NaN
5,Apartamento,Vista Alegre,3,1,0,70,1200.0,NaN,NaN
6,Apartamento,Cachambi,2,0,0,50,1300.0,301.0,17.0
...,...,...,...,...,...,...,...,...,...
32951,Apartamento,Vila Valqueire,2,0,0,52,1000.0,550.0,NaN
32953,Apartamento,Méier,2,0,0,70,900.0,490.0,48.0
32955,Quitinete,Centro,0,0,0,27,800.0,350.0,25.0
32956,Apartamento,Jacarepaguá,3,1,2,78,1800.0,800.0,40.0
32957,Apartamento,São Francisco Xavier,2,1,0,48,1400.0,509.0,37.0

Apagando  e removendo na filtragem  dos dados

In [ ]:
#Apresentado os registros com valores nulos
a = dados.shape[0]
dados[dados['Valor'].isnull()]
# Apagar os registros de fato
dados.dropna(subset = ['Valor'],inplace =  True)
# Como saber quantos registro apagamos, lembrando que tenho que roda tudo novamente.
b = dados.shape[0]
a-b

17